### ISSUE TITLE
Calling the resource server will always work since you permitAll() in Client Server

### ISSUE THREAD

**Issue by vunhatchuong** [nkchauhan003/spring-boot-oauth2-client-credentials-grant-type#1]
In your Client Server setting 
```java
@EnableWebSecurity
public class SecurityConfig {
 
    @Bean
    SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http
                .authorizeRequests()
                .antMatchers("/products-view/**").permitAll();
        return http.build();
    }
}
```

Since you `permitAll()` with product, everyone will be able to access it with or without token.

**Comment by nkchauhan003** [comment]
This is not an issue or bug.

The code you pasted here is from the client app, `spring-boot-api-client` and not from resource server.
We are trying to protect `spring-boot-resource-server` data in a server to server call.

This URL - /products-view/** from `spring-boot-api-client` is removing security from a web view but the data (from API) the view is using from `spring-boot-resource-server` is still protected.
